### ISSUE TITLE
Service and Message definitions for actions

### ISSUE THREAD

**Issue by sloretz** [ros2/rcl_interfaces#40]
## Feature request

This is a ticket to create message and service definitions for actions in the `rcl_interfaces` package.

#### Feature description

In the current proposal there are 3 services and 2 topics.

1. Send Goal Service
  Service generated for each action, nothing to add to rcl_interfaces
2. Cancel Goal Service
  **Same for all actions, could live in rcl_interfaces**
  Request is the goal id and a time stamp
  Response is a list of goal ids
3. Get Result Service
  Service generated for each action, generated service response will include enum goal status
4. Goal Status Topic
  **Same for all actions, could live in rcl_interfaces**
  List of (goal id,  the time the goal was accepted, and an enum for goal status)
5. Feedback Topic
  Message generated for each action, nothing to add to rcl_interfaces.

#### Implementation considerations

The state/status of a goal is used in two places: the status topic and the response to GetResult. It would be convenient if goal status constants were in a message that could be used by both.

```
# GoalStatus.msg
uint8 UNKNOWN=0
uint8 ACCEPTED=1
...
uint8 status
```

relates to ros2/design#193
connects to ros2/ros2#583

**Comment by jacobperron** [comment]
We might consider defining a `GoalDescription.msg` (analogous to [actionlib_msgs/GoalID.msg](https://github.com/ros/common_msgs/blob/jade-devel/actionlib_msgs/msg/GoalID.msg)) for reuse in all of the services and topics related to actions (generated or defined in rcl_interfaces). Suggesting the word "Description" instead of "ID" because it also contains a timestamp.

From the design doc, the plan is to use a UUID for the goal ID. There is the [uuid_msgs](https://github.com/ros-geographic-info/unique_identifier/tree/master/uuid_msgs) package from ROS 1. We can fork this as a core ROS 2 package along with helper libraries (e.g. [unique_id](https://github.com/ros-geographic-info/unique_identifier/tree/master/unique_id)) for working with UUIDs.

**Comment by jacobperron** [comment]
Ready for review.

I've opted for the shorter name `GoalInfo.msg` (instead of `GoalDescription.msg`), if anyone has a strong opinion about it I can change it easily.
